import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


data = pd.read_csv("final.csv", low_memory=False)
#Deleted everything with ID since we're containing names anyways ;)
print(data['passer_player_name'].unique())
print(data['receiver_player_name'].unique())
print(data['rusher_player_name'].unique())
print(data['lateral_receiver_player_name'].unique())
print(data['lateral_rusher_player_name'].unique())
print(data['lateral_sack_player_name'].unique())
print(data['interception_player_name'].unique())
print(data['lateral_interception_player_name'].unique())
print(data['punt_returner_player_name'].unique())
print(data['lateral_punt_returner_player_name'].unique())
print(data['lateral_kickoff_returner_player_name'].unique())
print(data['punter_player_name'].unique())
print(data['kicker_player_name'].unique())
print(data['own_kickoff_recovery_player_name'].unique())
print(data['blocked_player_name'].unique())
print(data['tackle_for_loss_1_player_name'].unique())
print(data['tackle_for_loss_2_player_name'].unique())
print(data['qb_hit_1_player_name'].unique())
print(data['qb_hit_2_player_name'].unique())
print(data['forced_fumble_player_1_player_name'].unique())
print(data['forced_fumble_player_2_player_name'].unique())
print(data['solo_tackle_1_player_name'].unique())
print(data['solo_tackle_2_player_name'].unique())
print(data['assist_tackle_1_player_name'].unique())
print(data['assist_tackle_2_player_name'].unique())
print(data['assist_tackle_3_player_name'].unique())
print(data['assist_tackle_4_player_name'].unique())
print(data['pass_defense_1_player_name'].unique())
print(data['pass_defense_2_player_name'].unique())
print(data['fumbled_1_player_name'].unique())
print(data['fumbled_2_player_name'].unique())
print(data['fumble_recovery_1_player_name'].unique())
print(data['fumble_recovery_2_player_name'].unique())
print(data['penalty_player_name'].unique())
print(data['penalty_type'].unique())
print(data['Weather'].unique())
print(data['WDirection'].unique())
print(data['HCoach'].unique())
print(data['HDefense'].unique())
print(data['HOffense'].unique())
print(data['ACoach'].unique())
print(data['ADefense'].unique())
print(data['AOffense'].unique())